print("sreekanth pradeep")
print("roll no:52")
import numpy as np
uninitialized_array=np.empty(shape=(2,3))
print("uninitialized array")
print(uninitialized_array )
ones_array = np.ones(shape=(2,3))
print("array with all elements as 1:")
print(ones_array)
zeros_array = np.zeros(shape=(2,3))
print("array with alle elements as o:")
print(zeros_array)